// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAM_IvJmts8n4US9E0OadoiagHnrwgag',
    appId: '1:258300359966:web:caa7213894838fed67050f',
    messagingSenderId: '258300359966',
    projectId: 'sreelalithapeetham-e53c7',
    authDomain: 'sreelalithapeetham-e53c7.firebaseapp.com',
    storageBucket: 'sreelalithapeetham-e53c7.firebasestorage.app',
    measurementId: 'G-PL7KTNJTS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTj8p43vxco1bB1eTqXE_X7uYgDUq6DU',
    appId: '1:258300359966:android:39e562461db6203b67050f',
    messagingSenderId: '258300359966',
    projectId: 'sreelalithapeetham-e53c7',
    storageBucket: 'sreelalithapeetham-e53c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYTH2pv_RU0uhpqHSpPF1GzYKxq4-YgrE',
    appId: '1:258300359966:ios:d8438dc36e792bcc67050f',
    messagingSenderId: '258300359966',
    projectId: 'sreelalithapeetham-e53c7',
    storageBucket: 'sreelalithapeetham-e53c7.firebasestorage.app',
    iosBundleId: 'com.example.lalithaPeetham',
  );
}
